FROM node:22-alpine AS build
WORKDIR /app
COPY package.json ./
COPY src ./src
COPY tests/integration/docker/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
RUN npm install
RUN npm run build:all

FROM node:22-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
